### ISSUE TITLE
ERROR: get_columns_in_relation macro not implemented for adapter devnull

### ISSUE THREAD

**Issue by jice-lavocat** [bachng2017/dbt-devnull#1]
Some macros such as `dbt_utils.union_relations` use an adapter method named `get_columns_in_relation` that is not implemented in the devnull adapter so far.

--
To reproduce, install `dbt_utils` and try something like the following:

Create two dumb models `model1` and `model2` then 

failing_model.sql:
```
  {{ dbt_utils.union_relations(
    relations = [
      ref('model1'),
      ref('model2')
      ]
  ) }}
```
--
To fix, in [impl.py](https://github.com/bachng2017/dbt-devnull/blob/main/dbt/adapters/devnull/impl.py) add the following method. 

```
    def get_columns_in_relation(self, relation: BaseRelation):
        return []
```

**Comment by bachng2017** [comment]
merged
